spring:
  application:
    name: betsanddice-tutorial
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jmx:
    enabled: true
  data:
    mongodb:
      uri: mongodb://admin_tutorial:XMOJocgKlmRHz2O@localhost:27017/tutorials?authSource=admin
      uuid-representation: standard

springdoc:
  swagger-ui:
    path: "/swagger-ui-custom.html"
    operationsSorted: method
  api-docs:
    enable: true
    path: "/api-docs"

server:
  port: 8098

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false

url:
  connection_timeout: 30000
  maxBytesInMemory: 30000000