spring:
  application:
    name: "betsanddice-craps"
  profiles:
    active: "dev"
  data:
    mongodb:
      #uri para bbdd local:
#      host: localhost
#      port: 27017
#      database: games
#      password: XMOJocgKlmRHz2O
#      username: admin_game
#      authentication-database: admin
      #uri para bbdd docker:
      host: betsanddice-mongodb
      port: 27017
      database: betsanddice
      password: XMOJocgKlmRHz2O
      username: admin_betsanddice
      authentication-database: admin
      uuid-representation: standard
  cloud:
    compatibility-verifier:
      enabled: false
  config:
    import: "optional:configserver:http://localhost:8071/"

server:
  port: 8095

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

springdoc:
  swagger-ui:
    path: "/swagger-ui-custom.html"
    operationsSorted: method
  api-docs:
    enable: true
    path: "/api-docs"

info:
  app:
    name: "betsanddice-craps"
    description: "Bet-And-Dice Craps Application"
    version: "1.0.0"