version: "3.7"

services:
  consul-server1:
    image: consul:1.15.2
    container_name: consul-server1
    restart: always
    volumes:
      - ./server1.json:/consul/config/server1.json:ro
    networks:
      apisix-dev:
        ipv4_address: 172.18.0.2
    ports:
      - '8500:8500'
      - '8600:8600/tcp'
      - '8600:8600/udp'
    command: 'agent -bootstrap-expect=3'

  consul-server2:
    image: consul:1.15.2
    container_name: consul-server2-dev
    restart: always
    volumes:
      - ./server2.json:/consul/config/server2.json:ro
    networks:
      apisix-dev:
        ipv4_address: 172.18.0.3
    command: "agent -bootstrap-expect=3"

  consul-server3:
    image: consul:1.15.2
    container_name: consul-server3-dev
    restart: always
    volumes:
      - ./server3.json:/consul/config/server3.json:ro
    networks:
      apisix-dev:
        ipv4_address: 172.18.0.4
    command: "agent -bootstrap-expect=3"

  betsanddice-mongodb:
    container_name: mongodb-betsanddice
    image: mongo:5.0.9
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_betsanddice
      MONGO_INITDB_ROOT_PASSWORD: XMOJocgKlmRHz2O
      MONGO_INITDB_DATABASE: users
    ports:
      - "27018:27017"
    volumes:
      - betsanddice_mongodb_data:/data/db
      #- data-mongo-bets-user:/var/lib/docker/volumes/data-mongo-bets-user/_data
      #- betsanddice_mongodb_data:/var/lib/mongodb
      #- ../betsandice-user/src/main/resources/mongodb-init:/docker-entrypoint-initdb.d
      #- ../betsandice-user/src/main/resources/mongodb-test-data:/tmp/data/
    networks:
      apisix-dev:
        ipv4_address: 172.18.0.5

  betsanddice-user:
    image: albertmart000/betsanddice:betsanddice-user-v1.0-SNAPSHOT
    container_name: betsanddice-user-v1.0-SNAPSHOT
    restart: always
    depends_on:
      - betsanddice-mongodb
    ports:
      - "8094:8094"
    environment:
      MONGODB_HOST=mongodb: 27017
      MONGODB_USERNAME: admin_betsanddice
      MONGODB_PASSWORD: XMOJocgKlmRHz2O
      MONGODB_CONTAINER_PORT: 27018
      MONGODB_USER_DATABASE: users

    # environment:
    #  - 'spring.data.mongodb.uri=mongodb://${MONGODB_CHALLENGE_USERNAME}:${MONGODB_CHALLENGE_PASSWORD}@172.18.0.5:${MONGODB_CONTAINER_PORT}/${MONGODB_CHALLENGE_DATABASE}?authSource=admin'

    networks:
      apisix-dev:
        ipv4_address: 172.18.0.6

  betsanddice-game:
    image: albertmart000/betsanddice:betsanddice-game-v1.0-SNAPSHOT
    container_name: betsanddice-game-v1.0-SNAPSHOT
    restart: always
    depends_on:
      - betsanddice-mongodb
    ports:
      - "8095:8095"
    environment:
      MONGODB_HOST=mongodb: 27017
      MONGODB_USERNAME: admin_betsanddice
      MONGODB_PASSWORD: XMOJocgKlmRHz2O
      MONGODB_CONTAINER_PORT: 27018
      MONGODB_CRAPS_DATABASE: game
    networks:
      apisix-dev:
        ipv4_address: 172.18.0.7

  betsanddice-tutorial:
    image: albertmart000/betsanddice:betsanddice-tutorial-v1.0-SNAPSHOT
    container_name: betsanddice-tutorial-v1.0-SNAPSHOT
    restart: always
    depends_on:
      - betsanddice-mongodb
    ports:
      - "8098:8098"
    environment:
      MONGODB_HOST=mongodb: 27017
      MONGODB_USERNAME: admin_betsanddice
      MONGODB_PASSWORD: XMOJocgKlmRHz2O
      MONGODB_CONTAINER_PORT: 27018
      MONGODB_TUTORIAL_DATABASE: tutorials
    networks:
      apisix-dev:
        ipv4_address: 172.18.0.8

  betsanddice-stat:
    image: albertmart000/betsanddice:betsanddice-stat-v1.0-SNAPSHOT
    container_name: betsanddice-stat-v1.0-SNAPSHOT
    restart: always
    depends_on:
      - betsanddice-mongodb
    ports:
      - "8096:8096"
    environment:
      MONGODB_HOST=mongodb: 27017
      MONGODB_USERNAME: admin_betsanddice
      MONGODB_PASSWORD: XMOJocgKlmRHz2O
      MONGODB_CONTAINER_PORT: 27018
      MONGODB_STAT_DATABASE: stats
    networks:
      apisix-dev:
        ipv4_address: 172.18.0.9

  betsanddice-nginx: #docker run -it -p 80:80 albertmart000/betsanddice:nginx-frontend-v1.0-SNAPSHOT
    container_name: nginx-betsanddice
    #image: albertmart000/betsanddice:nginx-frontend-v1.0-SNAPSHOT
    image: nginx
    restart: always
    ports:
      - "90:80"
    networks:
      apisix-dev:
        ipv4_address: 172.18.0.10
  apisix-gateway:
    container_name: apisix-gateway-dev
    image: apache/apisix:3.7.0-redhat
    restart: always
    volumes:
      - ./apisix_conf/apisix_standalone.yaml:/usr/local/apisix/conf/apisix.yaml:ro
    environment:
      APISIX_STAND_ALONE: true
    ports:
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
    networks:
      apisix-dev:
        ipv4_address: 172.18.0.10

volumes:
  betsanddice_mongodb_data:
    name: betsanddice_mongodb_data

networks:
  apisix-dev:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24