services:

  betsanddice-config:
    container_name: betsanddice-config-v1.0-SNAPSHOT
    image: albertmart000/betsanddice:betsanddice-config-v1.0-SNAPSHOT
    restart: always
    ports:
      - "8071:8071"
#    healthcheck:
#      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
#      interval: 15s
#      timeout: 5s
#      retries: 10
#      start_period: 30s
    extends:
      file: common-config.yml
      service: microservice-base-config

  betsanddice-eureka:
    container_name: betsanddice-eureka-v1.0-SNAPSHOT
    image: albertmart000/betsanddice:betsanddice-eureka-v1.0-SNAPSHOT
    restart: always
    ports:
      - "8070:8070"
    depends_on:
      - betsanddice-config
        #condition: service_healthy
#    healthcheck:
#      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
#      interval: 15s
#      timeout: 5s
#      retries: 10
#      start_period: 30s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: betsanddice-eureka

  betsanddice-user:
    container_name: betsanddice-user-v1.0-SNAPSHOT
    image: albertmart000/betsanddice:betsanddice-user-v1.0-SNAPSHOT
    restart: always
    ports:
      - "8094:8094"
    depends_on:
      - betsanddice-config
        #condition: service_healthy
      - betsanddice-eureka
        #condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: betsanddice-user
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  betsanddice-craps:
    container_name: betsanddice-craps-v1.0-SNAPSHOT
    image: albertmart000/betsanddice:betsanddice-craps-v1.0-SNAPSHOT
    restart: always
    ports:
      - "8095:8095"
    depends_on:
      - betsanddice-config
       # condition: service_healthy
      - betsanddice-eureka
       # condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: betsanddice-craps
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  network-betsanddice:
    driver: "bridge"